export enum LeveledRank{
    Base1 = 0,
    Base2 = 1,
    Base3 = 2,
    Bronze1 = 3,
    Bronze2 = 4,
    Bronze3 = 5,
    Silver1 = 6,
    Silver2 = 7,
    Silver3 = 8,
    Gold1 = 9,
    Gold2 = 10,
    Gold3 = 11,
    Gold4 = 12,
    Gold5 = 13,
    Apex1 = 14,
    Apex2 = 15,
    Apex3 = 16,
    Apex4 = 17,
    Apex5 = 18,
    MinorStar = 19,
    MediumStar = 20,
    MajorStar = 21,
    Supernova = 22,
    Iluminated = 23
}

export enum Rank{
    None,
    Base,
    Bronze,
    Silver,
    Gold,
    Apex,
    MinorStar,
    MediumStar,
    MajorStar,
    Supernova,
    Iluminated
}